
version: '3.7'

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: '2.7'
        NODE_VERSION: 'lts/*'
        PG_MAJOR: '12'
        BUNDLER_VERSION: '2.1.4'
    image: om30:1.0.0
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - bundle:/usr/local/bundle
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh
    environment:
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=5
      - DATABASE_URL=postgres://postgres:123456@postgresdb:5432
      - WEB_CONCURRENCY=1
      - HISTFILE=./log/.bash_history
      - EDITOR=vi
    depends_on:
      - postgresdb
      - mailcatcher

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3001:3000'
      - '3003:3002'
      - '7433:7433'

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3005:3000'
      - '9876:9876'

  postgresdb:
    image: postgres:12.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  bundle: